### ISSUE TITLE
Please, propose new services support here

### ISSUE THREAD

**Issue by maximkou** [maximkou/grav-plugin-videoembed#7]
Now, plugin supports `Youtube`, `Vimeo` and `Coub`.
In release `1.2.0` added `Vine.co`.

**Upd(21.09.2014):**
In release `1.3.0` added `self-hosted` videos support, using Video.JS

What more services support should be added?

**Comment by GrandM1961** [comment]
Would live ti see this plugin to support bitchute or other relative unknown video hosting services
